# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readFile <- function(filename) {
    .Call(`_MeshesOperations_readFile`, filename)
}

writeFile <- function(filename, binary, precision, Vertices, Faces) {
    invisible(.Call(`_MeshesOperations_writeFile`, filename, binary, precision, Vertices, Faces))
}

connectedComponentsK <- function(rmesh0, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_connectedComponentsK`, rmesh0, isTriangle, triangulate, clean, normals, epsilon)
}

connectedComponentsEK <- function(rmesh0, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_connectedComponentsEK`, rmesh0, isTriangle, triangulate, clean, normals, epsilon)
}

connectedComponentsQ <- function(rmesh0, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_connectedComponentsQ`, rmesh0, isTriangle, triangulate, clean, normals, epsilon)
}

SurfMesh <- function(rmesh, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_SurfMesh`, rmesh, isTriangle, triangulate, clean, normals, epsilon)
}

SurfEMesh <- function(rmesh, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_SurfEMesh`, rmesh, isTriangle, triangulate, clean, normals, epsilon)
}

SurfQMesh <- function(rmesh, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_SurfQMesh`, rmesh, isTriangle, triangulate, clean, normals, epsilon)
}

Intersection_K <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Intersection_K`, rmeshes, clean, normals)
}

Intersection_EK <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Intersection_EK`, rmeshes, clean, normals)
}

Intersection_Q <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Intersection_Q`, rmeshes, clean, normals)
}

Difference_K <- function(rmesh1, rmesh2, clean, normals) {
    .Call(`_MeshesOperations_Difference_K`, rmesh1, rmesh2, clean, normals)
}

Difference_EK <- function(rmesh1, rmesh2, clean, normals) {
    .Call(`_MeshesOperations_Difference_EK`, rmesh1, rmesh2, clean, normals)
}

Difference_Q <- function(rmesh1, rmesh2, clean, normals) {
    .Call(`_MeshesOperations_Difference_Q`, rmesh1, rmesh2, clean, normals)
}

Union_K <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Union_K`, rmeshes, clean, normals)
}

Union_EK <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Union_EK`, rmeshes, clean, normals)
}

Union_Q <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Union_Q`, rmeshes, clean, normals)
}

isotropicRemeshingK <- function(rmesh, targetEdgeLength, niters, nrelaxsteps, triangulate, normals) {
    .Call(`_MeshesOperations_isotropicRemeshingK`, rmesh, targetEdgeLength, niters, nrelaxsteps, triangulate, normals)
}

smoothMeshK <- function(rmesh, angle, niters, triangulate, normals) {
    .Call(`_MeshesOperations_smoothMeshK`, rmesh, angle, niters, triangulate, normals)
}

smoothShapeK <- function(rmesh, time, niters, triangulate, normals) {
    .Call(`_MeshesOperations_smoothShapeK`, rmesh, time, niters, triangulate, normals)
}

