# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gtest <- function(x) {
    .Call(`_MeshesOperations_gtest`, x)
}

gtest2 <- function(x) {
    .Call(`_MeshesOperations_gtest2`, x)
}

gtest3 <- function(x) {
    .Call(`_MeshesOperations_gtest3`, x)
}

SurfMesh <- function(rmesh, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_SurfMesh`, rmesh, isTriangle, triangulate, clean, normals, epsilon)
}

SurfEMesh <- function(rmesh, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_SurfEMesh`, rmesh, isTriangle, triangulate, clean, normals, epsilon)
}

SurfQMesh <- function(rmesh, isTriangle, triangulate, clean, normals, epsilon) {
    .Call(`_MeshesOperations_SurfQMesh`, rmesh, isTriangle, triangulate, clean, normals, epsilon)
}

Intersection_K <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Intersection_K`, rmeshes, clean, normals)
}

Intersection_EK <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Intersection_EK`, rmeshes, clean, normals)
}

Intersection_Q <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Intersection_Q`, rmeshes, clean, normals)
}

Difference_K <- function(rmesh1, rmesh2, clean, normals) {
    .Call(`_MeshesOperations_Difference_K`, rmesh1, rmesh2, clean, normals)
}

Difference_EK <- function(rmesh1, rmesh2, clean, normals) {
    .Call(`_MeshesOperations_Difference_EK`, rmesh1, rmesh2, clean, normals)
}

Difference_Q <- function(rmesh1, rmesh2, clean, normals) {
    .Call(`_MeshesOperations_Difference_Q`, rmesh1, rmesh2, clean, normals)
}

Union_K <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Union_K`, rmeshes, clean, normals)
}

Union_EK <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Union_EK`, rmeshes, clean, normals)
}

Union_Q <- function(rmeshes, clean, normals) {
    .Call(`_MeshesOperations_Union_Q`, rmeshes, clean, normals)
}

